# Continuous Deployment Workflow for Stage
name: deploy-to-ci
run-name: Continuous deployment triggered by ${{ github.event_name }}

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs:

  # Build static site using Reveal-MD
  build-ci:
    name: Build CI
    if: ${{ !github.event.client_payload.paused }}
    uses: dr3dr3/devops-via-preso/.github/workflows/reuse-build-revealmd.yml@main
    with: 
      target-ref: ${{ github.event.client_payload.target_ref }}
      deploy-target: 'ci'
    secrets: inherit

  # Deploy to GitHub Pages on the Stage Repo
  deploy-to-github-pages:
    name: Deploy GHP(CI)
    needs: build-ci
    uses: dr3dr3/devops-via-preso/.github/workflows/reuse-deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      target-ref: ${{ github.event.client_payload.target_ref }}
      deploy-target: 'ci'
    secrets: inherit