# Continuous Deployment Workflow
name: prod-deploy
run-name: Continuous deployment triggered by ${{ github.event_name }}

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy-stage]

jobs:
  # Add tag for next version
  test-echo:
    name: Add Tag
    if: ${{ !github.event.client_payload.paused }}
    timeout-minutes: 10
    runs-on: ubuntu-latest    
    steps:

      - name: Quick echo
        run: echo "Dispatch worked"


# JOBS:
# test live API's are responsive
# reuse-build-revealmd.yml
# clone out blue/green rego (per input)...
# ...delete _site folder
# ...copy _site folder from build to _site folder (replace above)
# ...changes to .github/workflows (if any)
# update AWS routing...
# ... 10% of traffic to new
# ... after 10 days no issues then 100%
# ... if issue, then 0% and sent alert and trigger rollback
# run PVT tests (alert if any issues)
