# Continuous Deployment Workflow
name: prod-caller-workflow
run-name: Continuous deployment triggered by ${{ github.event_name }}

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  # Build static site using Reveal-MD
  build-prod:
    name: Build PROD
    uses: ./.github/workflows/reuse-build-revealmd.yml
    with: 
      branch-name: ${{ github.ref_name }}
      deploy-stage: 'prod'


# JOBS:
# test live API's are responsive
# reuse-build-revealmd.yml
# clone out blue/green rego (per input)...
# ...delete _site folder
# ...copy _site folder from build to _site folder (replace above)
# ...changes to .github/workflows (if any)
# update AWS routing...
# ... 10% of traffic to new
# ... after 10 days no issues then 100%
# ... if issue, then 0% and sent alert and trigger rollback
# run PVT tests (alert if any issues)
